name: 'Guardian'
description: "A lightweight and accessible region plugin."
main: com.moderocky.guardian.Guardian
version: '1.2.1'
api-version: '1.15'
website: 'https://gitlab.com/Pandaemonium'
default-permission: true
author: Pandaemonium
authors:
  - Mackenzie (Moderocky)
